version: "3"

services:
  spring-rest-specialist-db:
    image: postgres:latest
    container_name: spring-rest-specialist-db
    networks:
      - spring-rest-specialist
    environment:
      - POSTGRES_DB=springrestspecialist
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"

networks:
  spring-rest-specialist:
    driver: bridge