spring:
  application:
    name: spring-rest-specialist
  datasource:
    url: jdbc:postgresql://localhost:5432/springrestspecialist
    username: postgres
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  sql:
    init:
      mode: always
  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true